### ISSUE TITLE
Why are files under resources/** BOM encoded?

### ISSUE THREAD

**Issue by sir-ragna** [AskiaADX/ADXStudio#1]
When starting a new project the files under `resources/**` are BOM encoded, the rest of the project is not. This shows in the editor as these files starting with a red dot.

Is there a reason behind this?

- [x] bug
- [ ] feature

**Comment by MamadouSy** [comment]
Hi Robbe,

Thanks for the feedback. 
There is no reason for the BOM, the creation of project is a copy of predefined template (creates in another IDE).
I guess I have to remove the BOM during the copy or during the display of the content.

Yes you can flag as bug.
Thanks again.

Mams

**Comment by MamadouSy** [comment]
Hi Robbe,

This should be fixed in the new 0.0.8 version.

Thanks again
