### ISSUE TITLE
Pound sign (£) not render correctly when included in a fixture

### ISSUE THREAD

**Issue by Djedj** [AskiaADX/ADXStudio#11]
Pound sign (£) not render correctly when included in a fixture

Take the template All and in the single.xml fixture, add the Pound sign (£) before and after the response A and check the preview. It shows question mark

**Comment by MamadouSy** [comment]
Hi Djedj,

The fixture is XML, you have to use the encoded entities (as for html) for special characters.
For the pound sign please try using the &#163;

Mamadou
