### ISSUE TITLE
Display bottom of editor

### ISSUE THREAD

**Issue by VincentTel** [AskiaADX/ADXStudio#14]
This bug involve files with a number of lines superior to the capacity of display of the editor.
when you scroll down, you can nearly see the full row :
![scroll-down](https://cloud.githubusercontent.com/assets/16402036/26717373/70f41ac8-477d-11e7-99d2-175a16b50760.PNG)
then when you click or write on it, the view goes up :
![write-down](https://cloud.githubusercontent.com/assets/16402036/26717422/a9b5c7b2-477d-11e7-948b-8d98c812ca02.PNG)

**Comment by VincentTel** [comment]
This problem is the same issue than the "View when search of a word #15" issue : this problem is associated to the resizing of the editor when the finder appears

**Comment by prabathgamage** [comment]
Resizing of the editor fixed the issue.
