### ISSUE TITLE
View when search of a word

### ISSUE THREAD

**Issue by VincentTel** [AskiaADX/ADXStudio#15]
When we search a word and we go to the next hint, it scroll down but not enougth. We don't see the word :
![find-behaviour](https://cloud.githubusercontent.com/assets/16402036/26717798/026a7672-477f-11e7-82e6-c06284c359a8.PNG)
Where the word is :
![position-match](https://cloud.githubusercontent.com/assets/16402036/26717803/0492cb70-477f-11e7-98a7-36b727aab60f.PNG)

This seem to not do the same thing when we go to the previous hint or if we go back to the first hint.

**Comment by prabathgamage** [comment]
Closed as same as the issue #14 (Display bottom of the editor).
