### ISSUE TITLE
"Save" button in the "Project settings" view

### ISSUE THREAD

**Issue by StephenPadawan** [AskiaADX/ADXStudio#2]
In this version, the changes to "Information", "Output" and "Properties" of a project only get reflected upon closing the project settings.
Can we add a "Save" button, so this the changes are pushed into **config.xml** while the project setting view is still open ?

**Comment by MamadouSy** [comment]
Hi Padawan,

We will probably do a split view for the config.xml.
Adding a toggle button "Code | Form" and no more display two tabs to modify the same file.

It will then be easier to update the "Form" or the "Code" according to the displayed view.
(If you are in "Code", switching to "Form" will update the "Form" with the code and vice-versa).

Thanks for the feedback.

**Comment by StephenPadawan** [comment]
V0.0.9 does provide a neat way of handling this. I'm closing the issue
