### ISSUE TITLE
Adding Outputs from the static folder causes a problem.

### ISSUE THREAD

**Issue by jackalds** [AskiaADX/ADXStudio#8]
When adding an output content from the static folder it relabels it incorrectly as "statics"

![capture](https://cloud.githubusercontent.com/assets/10074027/14204813/9ddbd71c-f7fe-11e5-810c-6176d78c612f.PNG)

**Comment by StephenPadawan** [comment]
Indeed, the config.xml states "statics" as well

![1](https://cloud.githubusercontent.com/assets/11921176/14490724/d0c03c7a-0174-11e6-9ca5-f983463eaa62.png)

And the drop down menu in the GUI also 

![2](https://cloud.githubusercontent.com/assets/11921176/14490745/f58e2c6a-0174-11e6-95fa-d70908404fcd.png)
